// <auto-generated />
using System;
using EduConnect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduConnect.Migrations
{
    [DbContext(typeof(EduConnectDbContext))]
    [Migration("20260605074930_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduConnect.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreditHours")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Code = "CS-101",
                            CreditHours = 3,
                            IsActive = true,
                            MaxCapacity = 30,
                            Title = "Introduction to Programming"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Code = "CS-201",
                            CreditHours = 3,
                            IsActive = true,
                            MaxCapacity = 30,
                            Title = "Data Structures"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Code = "CS-401",
                            CreditHours = 3,
                            IsActive = true,
                            MaxCapacity = 2,
                            Title = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Code = "CS-284",
                            CreditHours = 3,
                            IsActive = true,
                            MaxCapacity = 25,
                            Title = "Web Engineering"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Code = "SE-301",
                            CreditHours = 3,
                            IsActive = true,
                            MaxCapacity = 20,
                            Title = "Software Design Patterns"
                        });
                });

            modelBuilder.Entity("EduConnect.Models.FacultyCourse", b =>
                {
                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FacultyId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("FacultyCourses");

                    b.HasData(
                        new
                        {
                            FacultyId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            FacultyId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CourseId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            FacultyId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CourseId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            FacultyId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CourseId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            FacultyId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CourseId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        });
                });

            modelBuilder.Entity("EduConnect.Models.GradeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreditHours")
                        .HasColumnType("int");

                    b.Property<int>("Marks")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("GradeRecords");
                });

            modelBuilder.Entity("EduConnect.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EduConnect.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("People", (string)null);

                    b.HasDiscriminator<string>("Role").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EduConnect.Models.StudentCourse", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourses");

                    b.HasData(
                        new
                        {
                            StudentId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            StudentId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CourseId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            StudentId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CourseId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            StudentId = new Guid("66666666-6666-6666-6666-666666666666"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            StudentId = new Guid("66666666-6666-6666-6666-666666666666"),
                            CourseId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            StudentId = new Guid("77777777-7777-7777-7777-777777777777"),
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            StudentId = new Guid("88888888-8888-8888-8888-888888888888"),
                            CourseId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        });
                });

            modelBuilder.Entity("EduConnect.Models.Admin", b =>
                {
                    b.HasBaseType("EduConnect.Models.Person");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "admin@edu.pk",
                            FullName = "System Admin",
                            PasswordHash = "admin123"
                        });
                });

            modelBuilder.Entity("EduConnect.Models.Faculty", b =>
                {
                    b.HasBaseType("EduConnect.Models.Person");

                    b.HasDiscriminator().HasValue("Faculty");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Email = "ashfaq@edu.pk",
                            FullName = "Dr. Ashfaq",
                            PasswordHash = "faculty123"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Email = "sumera@edu.pk",
                            FullName = "Dr. Sumera",
                            PasswordHash = "faculty123"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Email = "ubaid@edu.pk",
                            FullName = "UbaidUllah",
                            PasswordHash = "faculty123"
                        });
                });

            modelBuilder.Entity("EduConnect.Models.Student", b =>
                {
                    b.HasBaseType("EduConnect.Models.Person");

                    b.Property<decimal>("CGPA")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Student");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Email = "usman@student.edu.pk",
                            FullName = "Usman",
                            PasswordHash = "student123",
                            CGPA = 3.6m,
                            Semester = 3
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Email = "rafiullah@student.edu.pk",
                            FullName = "Rafiullah",
                            PasswordHash = "student123",
                            CGPA = 3.2m,
                            Semester = 2
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Email = "daniyal@student.edu.pk",
                            FullName = "Daniyal",
                            PasswordHash = "student123",
                            CGPA = 3.4m,
                            Semester = 4
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Email = "fatima@student.edu.pk",
                            FullName = "Fatima",
                            PasswordHash = "student123",
                            CGPA = 2.9m,
                            Semester = 1
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Email = "ali@student.edu.pk",
                            FullName = "Ali Hassan",
                            PasswordHash = "student123",
                            CGPA = 3.0m,
                            Semester = 2
                        });
                });

            modelBuilder.Entity("EduConnect.Models.FacultyCourse", b =>
                {
                    b.HasOne("EduConnect.Models.Course", "Course")
                        .WithMany("FacultyCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Models.Faculty", "Faculty")
                        .WithMany("FacultyCourses")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("EduConnect.Models.GradeRecord", b =>
                {
                    b.HasOne("EduConnect.Models.Course", "Course")
                        .WithMany("GradeRecords")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduConnect.Models.Notification", b =>
                {
                    b.HasOne("EduConnect.Models.Person", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduConnect.Models.StudentCourse", b =>
                {
                    b.HasOne("EduConnect.Models.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Models.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduConnect.Models.Course", b =>
                {
                    b.Navigation("FacultyCourses");

                    b.Navigation("GradeRecords");

                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("EduConnect.Models.Faculty", b =>
                {
                    b.Navigation("FacultyCourses");
                });

            modelBuilder.Entity("EduConnect.Models.Student", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("StudentCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
